### ISSUE TITLE
Code smells detected by SonarCloud

### ISSUE THREAD

**Issue by makkbalazs** [BME-MIT-IET/Ford-iet-2020#7]

**Comment by makkbalazs** [comment]
Since yesterday 22:27:
Removed unused import java.util.Iterator in main/src/com/complexible/common/beans/Beans.java,

Removed unused method isPrimitive(Class theObj) in main/src/com/complexible/common/beans/Beans.java,

Replaced assertTrue(aPerson.id() != null); to assertNotNull(aPerson.id()); in testWriteSetsIdentifiableId() in test/src/com/complexible/pinto/RDFMapperTests.java,

Renamed _implements method to implementsInterface in main/src/com/complexible/common/reflect/Classes.java,

Did refactoring in readvalue method, more needed in main/src/com/complexible/pinto/RDFMapper.java,

replaced if-else with single return in isIgnored(final PropertyDescriptor thePropertyDescriptor) in main/src/com/complexible/pinto/RDFMapper.java,

Merged unneceserily separate if and else if in pinpointclass method in main/src/com/complexible/pinto/RDFMapper.java,

Replaced Throwable with Exception in catches in main/src/com/complexible/pinto/RDFMapper.java,

merged single if statement with the one containing it in pinpointclass method in main/src/com/complexible/pinto/RDFMapper.java,

Added ("Test not implemented") to Ignore-s, where test is not implemented. in test/src/com/complexible/pinto/RDFMapperTests.java.

**Comment by Mmate99** [comment]
#10 Megoldotta
